export const pashto = {
  nearbyStudios: "نیژدې کلپونه",
  healthTopics: "د روغتیا په اړه مقالې",
  changeProfilePicture: "د پروفایل عکس بدلول",
  changeUserName: "د نوم بدلول",
  changeEmail: "د اېمل آدرس بدلول",
  changeFacebookId: "د فیسبوک آی ډي بدلول",
  changeSportType: "د خوښې ورزش ټاکل",
  changeLocation: "د ځای بدلول",
  stepCounter: "د قدمو شمېرونکی",
  aboutUs: "د موږ په اړه",
  privacyPolicy: "د خصوصي حریم سیاست",
  darkMode: "تیاره بڼه",
  settings: "تنظیمات",
  logOut: "وتل",
  change: "بدل یې کړئ",
  newUserName: "نوی کارېدونکی نوم",
  changingUserName: "کارېدونکی نوم بدلوئ؟",
  areYouSure: "آیا مطمیئن یئ!",
  noCancel: "نه، بېرته وګرځئ",
  yesIAmSure: "او، مطمیئن یم",
  newEmail: "نوی اېمېل آدرس",
  home: "کور",
  profile: "پېژنیال",
  userName: "کاروونکی نوم",
  email: "برېښنالیک",
  location: "ځای",
  qrCode: "QR کود ",
  subscription: "قرارداد",
  feedBack: "کتنې",
  rateThisApp: "دغه کاریال ته درجه ورکئ",
  bmiCalculator: "د ‌BMI محسابه کول",
  bmiSentence: "pashto",
  check: "ویې ګورئ",
  studio: "کلپ",
};

export const dari = {
  nearbyStudios: "کلپ های نزدیک",
  healthTopics: "مقاله ها در مورد صحت",
  changeProfilePicture: "تبدیل نمودن عکس پروفایل",
  changeUserName: "تبدیل نمودن نام کاربری",
  changeEmail: "تبدیل نمودن ایمل آدرس",
  changeFacebookId: "تبدیل نمودن آی دی فیسبوک",
  changeSportType: "تبدیل نمودن ورزش مورد علاقه",
  changeLocation: "تبدیل نمودن موقعت",
  stepCounter: "قدم شمار",
  aboutUs: "در مورد ما",
  privacyPolicy: "سیاست حریم خصوصی",
  darkMode: "شکل تاریک",
  settings: "تنظیمات",
  logOut: "خارج شدن",
  change: "تبدیل کنید",
  newUserName: "نام کاربری جدید",
  changingUserName: "نام کاربری را تبدیل میکنید؟",
  areYouSure: "آیا مطمیئن هستید!",
  noCancel: "نه، عقب بروید",
  yesIAmSure: "بلی، مطمیئن هستم!",
  newEmail: "ایمل آدرس جدید",
  home: "خانه",
  profile: "پروفایل",
  userName: "نام کاربردی",
  email: "ایمل",
  location: "موقعت",
  qrCode: "QR کود",
  subscription: "قرارداد",
  feedBack: "باز خورد",
  rateThisApp: "به این برنامه درجه دهید",
  bmiCalculator: "حساب کردن BMI",
  bmiSentence: "dari",
  check: "ببینید",
  studio: "کلپ",
};

export const english = {
  nearbyStudios: "Nearby Studios",
  healthTopics: "Health Topics",
  changeProfilePicture: "Change Profile Picture",
  changeUserName: "Change Username",
  changeEmail: "Change Email",
  changeFacebookId: "Change Facebook Id",
  changeSportType: "Change Sport Type",
  changeLocation: "Change Location",
  stepCounter: "Step Counter",
  aboutUs: "About Us",
  privacyPolicy: "Privacy Policy",
  darkMode: "Dark Mode",
  settings: "Settings",
  logOut: "Log Out",
  change: "Change",
  newUserName: "New Username",
  changingUserName: "Changing Username?",
  areYouSure: "Are you sure!",
  noCancel: "No, cancel",
  yesIAmSure: "Yes, I am sure!",
  newEmail: "New Email",
  home: "Home",
  profile: "Profile",
  userName: "User Name",
  email: "Email",
  location: "Location",
  qrCode: "QR Code",
  subscription: "Subscription",
  feedBack: "Feedback",
  rateThisApp: "Rate this App",
  bmiCalculator: "BMI Calculator",
  bmiSentence: "english",
  check: "Check",
  studio: "Studio",
};
